### ISSUE TITLE
Batch Normalization Layer causes initializer error.

### ISSUE THREAD

**Issue by jadenyjw** [tflearn/tflearn#512]
The line `network = batch_normalization(network)` produces the following error with Tensorflow-GPU 0.12.0rc1.

`Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/tflearn/variables.py", line 52, in variable
    collections=collections)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for argument 'dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 48, in <module>
    network = batch_normalization(network)
  File "/usr/lib/python3.5/site-packages/tflearn/layers/normalization.py", line 91, in batch_normalization
    restore=restore)
  File "/usr/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/lib/python3.5/site-packages/tflearn/variables.py", line 58, in variable
    collections=collections)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for argument 'dtype'
`

**Comment by aymericdamien** [comment]
Thanks for reporting that bug, we are working on supporting TensorFlow 0.12. You may use TensorFlow 0.11rc2 in the meantime.

**Comment by ibadami** [comment]
Hi 
I had a similar problem and taking the advice here i changed my tenorflow to 0.11rc2, but now I am getting another error message, 
```

Traceback (most recent call last):
  File "test_resnet.py", line 37, in <module>
    net = tflearn.residual_bottleneck(net, 3, 16, 64)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/layers/conv.py", line 830, in residual_bottleneck
    resnet = tflearn.batch_normalization(resnet)
  File "/home/badami/Codes/deeplearning/tensorflow3/lib/python3.4/site-packages/tflearn/layers/normalization.py", line 84, in batch_normalization
    mean, var = tf.python.control_flow_ops.cond(
AttributeError: 'module' object has no attribute 'control_flow_ops'
```
This I guess is corresponding to the initial tensorflow bug regarding ones_initializer(). 
They fixed the bug only in 0.12 version. So we cannot use tflearn until this issue is fixed for tensorflow 0.12 :(

**Comment by ibadami** [comment]
@jadenyjw 
Did you have any luck using batch_normalization?

**Comment by MartinThoma** [comment]
I have Tensorflow `1.0.0` (`python -c "import tensorflow;print(tensorflow.__version__)"`). Same problem.

**Comment by ibadami** [comment]
@aymericdamien Hi could you please reply to my problem. I do not want to use tensorflow 1.0.0, it is too slow and I cannot find the way to fix this problem in 011rc1, 011rc2, 0.12.
