### ISSUE TITLE
Will Tflearn support Tensorflow 2.0?

### ISSUE THREAD

**Issue by EchoRickZz** [tflearn/tflearn#1121]
TF 2.0 has come, and i wonder if tflearn still support it?

**Comment by godka** [comment]
Same

**Comment by neversay** [comment]
Same, under 
tflearn/variables.py
I got error with tensorflow 2.0
from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope

since tesnorflow 2.0 has no contrib package anymore.

**Comment by MGM95** [comment]
are there any alternatives for the time being? I need to use the vocab processor from tflearn in my project.

**Comment by rahul-72** [comment]
Same, I got ERROR while importing `tflearn` in `tensorflow 2.0`

**Comment by ZekeXu** [comment]
No maintainer forever?

**Comment by godka** [comment]
Maybe it's time to push us to use tf-keras instead of tflearn.

**Comment by mrgokuji** [comment]
tflearn is not working with tensorflow 2.0.
just like keras ("from tensorflow.keras.models import Sequential") are we suppose to do something like this to import tflearn??

need urgent help!!

**Comment by mrgokuji** [comment]
guys I had a problem in importing tflearn..
I had installed the driver of nvidia graphic and then re-installed tf gpu and tflearn and now its working fine.

Hope your problems might get solved .

**Comment by viotemp1** [comment]
I'm trying with TF 2.0 and I have this error. Any idea how to solve it?
File "/mnt/data/virtualenvs/tf2/lib/python3.6/importlib/_bootstrap.py", line 626, in _load_backward_compatible
  spec.loader.load_module(spec.name)
File "/mnt/data/virtualenvs/tf2/lib/python3.6/site-packages/tflearn-0.3.2-py3.6.egg/tflearn/helpers/summarizer.py", line 12, in <module>
  merge_summary = tf.merge_summary

builtins.AttributeError: module 'tensorflow' has no attribute 'merge_summary'
Thanks

**Comment by RadicalAjay** [comment]
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> import tflearn
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/helpers/summarizer.py", line 9, in <module>
    merge_summary = tf.summary.merge
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'merge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tflearn
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/__init__.py", line 8, in <module>
    from . import models
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/models/__init__.py", line 2, in <module>
    from .dnn import DNN
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/models/dnn.py", line 6, in <module>
    from ..helpers.trainer import Trainer
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/helpers/__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/helpers/evaluator.py", line 9, in <module>
    from .trainer import evaluate_flow
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/helpers/trainer.py", line 20, in <module>
    from .summarizer import summaries, summarize, summarize_gradients, \
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tflearn/helpers/summarizer.py", line 12, in <module>
    merge_summary = tf.merge_summary
AttributeError: module 'tensorflow' has no attribute 'merge_summary'

**Comment by AlucardNosferatu** [comment]
I have to rewrite the model with Keras...

**Comment by aymericdamien** [comment]
TensorFlow 2.0+ support was added on the latest TFLearn version, using tf.compat.v1 api.
