### ISSUE TITLE
ImportError: cannot import name config

### ISSUE THREAD

**Issue by apoorvapantoola** [tflearn/tflearn#1042]
Hi ,
When I am trying to import tflearn i am getting the following error 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-31-1dcc0aeffa10> in <module>()
----> 1 import tflearn

/Applications/anaconda2/lib/python2.7/site-packages/tflearn/__init__.py in <module>()
      2 
      3 # Config
----> 4 from . import config
      5 from .config import is_training, get_training_mode, init_graph
      6 

ImportError: cannot import name config

Please help .
Thank you
PS: tensorflow is working fine

**Comment by apoorvapantoola** [comment]
the problem got resolved when i updated my python version from 2.7 to 3.6
