### ISSUE TITLE
import tflearn error: AttributeError: module 'pandas' has no attribute 'computation'

### ISSUE THREAD

**Issue by ebonat** [tflearn/tflearn#766]
After installing tflearn in windows 10. 

For the line of code: 

`import tflearn`

I got  the error:

```
Traceback (most recent call last):
  File "C:\Users\Ernest\git\test-code\test-code\src\tflearn_quick_start\main.py", line 5, in <module>
    import tflearn
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\__init__.py", line 30, in <module>
    from tensorflow.contrib import factorization
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\factorization\__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\factorization\python\ops\gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 87, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_io\dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\dask\dataframe\core.py", line 36, in <module>
    pd.computation.expressions.set_use_numexpr(False)
**AttributeError: module 'pandas' has no attribute 'computation'**
```
I use the following versions:

```
TensorFlow: 1.1.0-rc2
pandas: 0.20.1
```

Any help?

**Comment by iblis17** [comment]
http://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html#modules-privacy-has-changed

Use older pandas ?

**Comment by ebonat** [comment]
Why I need to get back to older pandas 0.19.2?  I need 0.20.1 version for all my projects at this time. Can the team update TFLearn so it can work with new pandas 0.20.1? All my clients are using 0.20.1 because it was very necessary for them. 

I really hope you can update TFLearn very soon! TFLearn is a very cool tool for Data Scientist today!

Thank you for all your help,

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by ppwwyyxx** [comment]
You can solve it by upgrading dask to 0.15.

**Comment by Dyex** [comment]
Had the same issue with prettytensor. Solved by running
pip install dask --upgrade

**Comment by zelong430** [comment]
I had the same problem. Upgrade dask solved it.

**Comment by tianyiwangnova** [comment]
Upgrading dask does work!

**Comment by Faaaaany** [comment]
upgrading dask with 'conda update dask" sovles my problem as well.

**Comment by Dyex719** [comment]
I just checked creating a virtual environment on Ubuntu 16.04 and simply
pip install tensorflow
pip install tflearn
works fine.

Which version of dask were you guys on before upgrading? 
Is this an issue particular to windows?

**Comment by sreeras** [comment]
Upgrading dask sloved the problem.

**Comment by ek-nath** [comment]
I am running this on python3.6 in Windows 10 and I get an error when I use the recommended installation steps:
`conda install -c bokeh datashader`
Output:
<pre><code>Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\guest\Anaconda3:

The following NEW packages will be INSTALLED:

    colorcet:   1.0.0-py36h86301b6_0 bokeh
    param:      1.5.1-py36_0

The following packages will be UPDATED:

    conda:      4.3.24-py36_0        conda-forge --> 4.3.27-py36hcbae3bd_0
    datashader: 0.4.0-py36_0                     --> 0.6.1-py36_0          bokeh

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env:  2.6.0-0              conda-forge --> 2.6.0-0</code></pre>

Using `conda upgrade dask` solved the problem

<pre><code>Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\guest\Anaconda3:

The following NEW packages will be INSTALLED:

    dask-core:        0.15.3-py36hd651449_0
    distributed:      1.19.1-py36h8504682_0
    msgpack-python:   0.4.8-py36h58b1e9d_0
    sortedcontainers: 1.5.7-py36ha90ac20_0
    tblib:            1.3.2-py36h30f5020_0
    zict:             0.1.3-py36h2d8e73e_0

The following packages will be UPDATED:

    conda-env:        2.6.0-0               --> 2.6.0-h36134e3_1
    dask:             0.13.0-py36_0         --> 0.15.3-py36h396fcb9_0
    partd:            0.3.7-py36_0          --> 0.3.8-py36hc8e763b_0
    tornado:          4.4.2-py36_0          --> 4.5.2-py36h57f6048_0</pre></code>

**Comment by sotoglzz** [comment]
I had the same problem. Upgrade dask solved it. Thank you so much
:D

**Comment by aptr288** [comment]
Problem was solved thanks a lot Faaany  and alll

**Comment by grayhaired** [comment]
conda upgrade dask 
worked for me as well..

**Comment by xiaoli-chen** [comment]
pip install dask --upgrade solved my problems, thank you all

**Comment by MichalHek** [comment]
pip install dask --upgrade solved it. Thanks!!!

**Comment by xjdeng** [comment]
```conda upgrade dask``` if you're using Anaconda

**Comment by temami** [comment]
conda upgrade dask
worked for me too
thanks

**Comment by ynuwm** [comment]
> Had the same issue with prettytensor. Solved by running
> pip install dask --upgrade

Thank you! Great~
