### ISSUE TITLE
Can't import tflearn 

### ISSUE THREAD

**Issue by jandziak** [tflearn/tflearn#619]
Hi I just installed tflearn and upgraded tensorflow and I can not import tflearn.
I am using python 2.7, anaconda, gpu supported version of tensorflow

I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/home/jan/Tensorflow/Tensorflow_module_1.py", line 1, in <module>
    import tflearn
  File "/home/jan/anaconda2/lib/python2.7/site-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/home/jan/anaconda2/lib/python2.7/site-packages/tflearn/layers/__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/home/jan/anaconda2/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 10, in <module>
    from tensorflow.python.ops.rnn import rnn_cell_impl as _rnn_cell, \
ImportError: cannot import name rnn_cell_impl

Do you have any solution for this? Tried to look for any similar problems in internet but didn't find any answer.

**Comment by Barnonewdm** [comment]
I have the same question.

**Comment by aymericdamien** [comment]
Are you using TensorFlow 1.0? Please follow instructions here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

**Comment by jandziak** [comment]
Thanks a lot, for me it helps. I tried to upgrade tensorflow before, but it
didnt work but using this tutorial it is ok.

**Comment by deepakagrawal** [comment]
I am having the same error.
PS: I am using ubuntu with anaconda python 2.7

**Comment by kurah** [comment]
That page you linked doesn't seem to exist anymore....I am currently getting this same error

**Comment by CruzzRazor** [comment]
tensorflow doesn't works on python 2.7
please install 3.5.2 version to use tensorflow
