### ISSUE TITLE
Issue with quickstart tutorial

### ISSUE THREAD

**Issue by davepowell** [tflearn/tflearn#395]
Just installed TFlearn into a Python 2.7 environment.

Stepping through the quickstart tutorial, I get stuck at:

net = tflearn.fully_connected(net, 32)

I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tflearn/layers/core.py", line 146, in fully_connected
    with tf.variable_scope(scope, name, values=[incoming], reuse=reuse) as scope:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(_args, *_kwds))
TypeError: variable_scope() got an unexpected keyword argument 'values'

Any help would be appreciated.

**Comment by OlivierData** [comment]
Which version of tensorflow is installed ?
`pip show tensorflow`

**Comment by aymericdamien** [comment]
Your tensorflow version is too old, please update to TensorFlow 0.10. Note that currently TensorFlow 0.11 has a bug when saving/restoring a model, so 0.10 version is advised.

**Comment by ekerazha** [comment]
Same issue with Python 3.5, tensorflow 0.10.0 and tflearn bleeding edge version, while I try to run the cnn_sentence_classification.py example.

**Comment by aymericdamien** [comment]
Actually, it seems that it is working with TF 0.10 but not with TF 0.10rc0. I will add special exceptions to handle older TF versions.

**Comment by davepowell** [comment]
I actually downgraded to 0.9 following the installation instructions.  I'll go back up to 0.10 and give it a try.

**Comment by davepowell** [comment]
I tried the upgrade and same issue unfortunately.  Here is the error:

>>> net = tflearn.fully_connected(net, 32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tflearn/layers/core.py", line 146, in fully_connected
    with tf.variable_scope(scope, name, values=[incoming], reuse=reuse) as scope:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got an unexpected keyword argument 'values'
>>> quit()


And here is the tensorflow version info:

Metadata-Version: 2.0
Name: tensorflow
Version: 0.10.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: six, mock, protobuf, wheel, numpy
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.tensorboard:main

**Comment by ekerazha** [comment]
I'm also on tensorflow 0.10.0, not 0.10rc0.

**Comment by tgallice** [comment]
This is because you use the TFLearn official release, probably 0.2.2. The fix was added after. Use the bleeding edge version should fix the issue.

```
pip install git+https://github.com/tflearn/tflearn.git
```

**Comment by davepowell** [comment]
Thanks for the update - I will give that a try.

**Comment by davepowell** [comment]
I updated to tflearn 2.2 and tensorflow 0.11 rc2 for python2 and it worked fine.
Thanks for your help.  
Closing

**Comment by adhirmndl** [comment]
![entry](https://user-images.githubusercontent.com/17833384/55872302-46172280-5baa-11e9-9f11-bab568bfad45.jpg)


Please help
